import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { TERMS_UPDATED_LABEL } from "@/lib/legal";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated={TERMS_UPDATED_LABEL}>
      <LegalSection title="The service">
        <p>
          Outrun is an AI growth platform that analyzes your business,
          identifies growth opportunities, finds and researches prospective
          customers, and generates outreach on your behalf.
        </p>
      </LegalSection>

      <LegalSection title="Eligibility">
        <p>
          You must be at least 18 years old and able to form a binding
          contract to use Outrun. If you&apos;re using Outrun on behalf of a
          business, you confirm you&apos;re authorized to accept these Terms
          for that business, and &ldquo;you&rdquo; in these Terms then means
          both you and that business.
        </p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          You&apos;re responsible for the accuracy of the information you give
          Outrun and for keeping your account credentials secure. You&apos;re
          responsible for all activity that happens under your account,
          including from teammates you invite.
        </p>
      </LegalSection>

      <LegalSection title="Subscriptions and billing">
        <p>
          Paid plans are billed through Paddle. You can cancel anytime from
          your Billing page; cancellation takes effect at the end of your
          current billing period. Except where required by law, fees already
          paid are non-refundable.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>
          You agree not to use Outrun to send outreach that is deceptive,
          impersonates someone else, or violates applicable anti-spam,
          telemarketing, or privacy laws in your or your prospects&apos;
          jurisdiction (for example CAN-SPAM, POPIA, or GDPR). You&apos;re
          solely responsible for how you use the outreach content, prospect
          data, and recommendations Outrun generates, including obtaining any
          consent or having any legal basis required before contacting a
          prospect.
        </p>
        <p>
          You also agree not to: attempt to reverse-engineer or scrape
          Outrun; use Outrun to build a competing product; interfere with the
          service&apos;s security or normal operation; or use Outrun for any
          unlawful purpose.
        </p>
      </LegalSection>

      <LegalSection title="Third-party and AI-generated data">
        <p>
          Growth Blueprints, prospect research, lead data, and outreach
          messages are generated by AI, or sourced from third-party
          directories (such as OpenStreetMap, Yelp, or Google Places), based
          on information available at the time. Outrun separates observed
          facts from AI inferences and assumptions wherever possible, but
          none of this content is guaranteed to be accurate, complete, or
          current — you&apos;re responsible for independently verifying it
          before relying on it, acting on it, or sending it to a third party.
        </p>
      </LegalSection>

      <LegalSection title="No guarantee of results">
        <p>
          Outrun helps you identify and act on growth opportunities. We
          don&apos;t guarantee any particular business outcome, lead quality,
          response rate, or revenue result from using the service.
        </p>
      </LegalSection>

      <LegalSection title="Disclaimer of warranties">
        <p>
          Outrun is provided &ldquo;as is&rdquo; and &ldquo;as
          available,&rdquo; without warranties of any kind, whether express,
          implied, or statutory, including any implied warranties of
          merchantability, fitness for a particular purpose, title, or
          non-infringement. We don&apos;t warrant that the service will be
          uninterrupted, error-free, or secure, or that any AI output, third
          party data, or lead information will be accurate.
        </p>
      </LegalSection>

      <LegalSection title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, Outrun and its owners,
          employees, and contractors won&apos;t be liable for any indirect,
          incidental, special, consequential, exemplary, or punitive
          damages, or for any loss of profits, revenue, data, or goodwill,
          arising from or related to your use of the service — even if
          advised of the possibility of such damages.
        </p>
        <p>
          To the maximum extent permitted by law, our total aggregate
          liability arising out of or relating to these Terms or the service
          is limited to the greater of (a) the amount you paid Outrun in the
          12 months before the claim, or (b) $100 USD.
        </p>
      </LegalSection>

      <LegalSection title="Indemnification">
        <p>
          You agree to indemnify, defend, and hold harmless Outrun and its
          owners, employees, and contractors from any claim, liability,
          damage, loss, or expense (including reasonable legal fees) arising
          out of or related to: your use of the service; outreach or other
          content you send using Outrun; your violation of these Terms; your
          violation of any law or third party&apos;s rights, including
          anti-spam, telemarketing, privacy, or data protection law; or
          content or data you submit to Outrun.
        </p>
      </LegalSection>

      <LegalSection title="Termination">
        <p>
          You may stop using Outrun and cancel your subscription at any time.
          We may suspend or terminate accounts that violate these Terms,
          create risk or legal exposure for us, or are inactive for an
          extended period, with notice where practical.
        </p>
      </LegalSection>

      <LegalSection title="Dispute resolution">
        <p>
          If a dispute arises, we&apos;ll first try to resolve it informally
          — contact us at the email below before filing a claim. Any dispute
          that can&apos;t be resolved informally is subject to the exclusive
          jurisdiction of the courts of South Africa.
        </p>
      </LegalSection>

      <LegalSection title="Governing law">
        <p>
          These Terms are governed by the laws of South Africa, without
          regard to its conflict of law principles.
        </p>
      </LegalSection>

      <LegalSection title="Changes to these terms">
        <p>
          We may update these Terms from time to time. We&apos;ll post the
          updated version here with a new &ldquo;Last updated&rdquo; date;
          material changes may require you to re-accept before continuing to
          use Outrun. Continued use of the service after a change takes
          effect constitutes acceptance of the updated Terms.
        </p>
      </LegalSection>

      <LegalSection title="Severability and entire agreement">
        <p>
          If any provision of these Terms is found unenforceable, the rest
          remain in full effect. These Terms, together with our{" "}
          <Link href="/privacy" className="text-[var(--color-accent-text)] underline">
            Privacy Policy
          </Link>
          , are the entire agreement between you and Outrun regarding the
          service.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>Questions about these terms: outrunv1privacy@outlook.com.</p>
      </LegalSection>
    </LegalPage>
  );
}
